account/urls.py
from django.urls import path
from .views import *

app_name = 'account'
urlpatterns = [
    path('signup/', signup, name='signup'),
]

doseonsaSupporters/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webzine/', include('webzine.urls')),
    path('', main, name='main'),
    path('users/', include('users.urls')),
    path('account/', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from re import template
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

webzine/urls.py
# webzine > urls.py

from unicodedata import name
from django.urls import path
from .views import * # webzine>views의 모든 함수를 가져옴.
from django.conf import settings
from django.conf.urls.static import static

app_name = "webzine"
urlpatterns = [
    path('webzine', webzine, name='webzine'),
    path('question_list', question_list, name='question_list'),
    path('<int:question_id>', question_detail, name="question_detail"),
    path('question_create', question_create, name="question_create"),
    path('answer/create/<int:question_id>', answer_create, name="answer_create"),
    path('webzine_upload/', webzine_upload, name='webzine_upload'),
    # path('webzine/', upload_create, name="upload_create"),
] 

# 업로드 구현을 해야하고 
# 
'''
업로드 구현해야하고 이미지가 여러개가 묶여있으니까 그거 다 불러와야하고 for문
안에 어떻게 꾸며질지 구상해야함.
'''

account/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

webzine/models.py
from distutils.command.upload import upload
from importlib.resources import contents
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200, null=False)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now=True)

class WebzineContents(models.Model):
    title = models.CharField(max_length=100, null=False)
    contents = models.TextField(null=True)
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Photo(models.Model):
    post = models.ForeignKey(WebzineContents, on_delete=models.CASCADE, null=True)
    cardnews = models.ImageField(upload_to='images/', null=True)

users/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

webzine/forms.py
from django import forms
from webzine.models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        # labels 코드 추가하기
        labels = {
            'subject' : '제목',
            'content' : '내용',
        }

account/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User

# Create your views here.

def signup(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['confirm']:
            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password'],
            )
            auth.login(request, user)
            return redirect('/')
        return render(request, 'signup.html')
    return render(request, 'signup.html')

doseonsaSupporters/views.py
# views.py

from django.shortcuts import render

def main(request):
    return render(request, 'main.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from users.forms import UserForm

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserForm()
    return render(request, 'users/signup.html', {'form': form})

webzine/views.py
from urllib import request
from django.shortcuts import render, get_object_or_404, redirect
from .models import Answer, Question, Photo, WebzineContents
from .forms import QuestionForm
from django.core.paginator import Paginator

# from django.views import generic
# Create your views here.
def webzine(request):
    return render(request, 'webzine/webzine.html')

def question_list(request):
    # q = Question.objects.all()
    questions = Question.objects.order_by('-create_date')
    # Paging 기능 구현하기
    page = request.GET.get('page', '1')
    paginator = Paginator(questions, 5)
    page_obj = paginator.get_page(page)
    context = {'question_list' : page_obj}
    return render(request, 'webzine/question_list.html', context)

def question_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'a_question' : question }
    return render(request, 'webzine/question_detail.html', context)

# class ListView(generic.ListView):
#     def get_queryset(self):
#         return Question.objects.order_by('-create_date')

# class DetailView(generic.DetailView):
#     model = Question

def question_create(request):
    if request.method == 'POST':
        a_form = QuestionForm(request.POST)
        if a_form.is_valid():
            question = a_form.save(commit=False)
            question.save()
            return redirect('webzine:question_list')
    else:
        a_form = QuestionForm()
    context = {'form' : a_form}
    return render(request, 'webzine/question_form.html', context)

def answer_create(request, question_id):
    a_question = get_object_or_404(Question, pk=question_id)
    a_content = request.POST.get('content')
    Answer.objects.create(question = a_question, content=a_content)
    return redirect('webzine:question_detail', question_id=a_question.id)

def webzine_upload(request):
    return render(request, 'webzine:webzine_upload.html')

def upload_create(request):
    form = WebzineContents()
    form.title = request.POST['title']
    try:
        form.image = request.FILES['image']
    except:
        pass
    form.save()
    return redirect('/')

doseonsaSupporters/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>base</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
</head>
<body>
    <!-- 네브바 위치 -->
    {% include 'shared/_navbar.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

doseonsaSupporters/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>
    {% include 'shared/_navbar.html' %}
    <div class="menu_wrap">
        <a href="#"><span class="give">혜명복지원 후원 바로가기</span></a>
        <ul class="menu">
            <li><a href="{% url 'webzine:webzine'%}">종무 행정</a></li>
            <li><a href="#">법회 / 행사 / 제사</a></li>
            <li><a href="{% url 'webzine:question_list'%}">교육 포교</a></li>
            <li><a href="#">오시는 길</a></li>
        </ul>
    </div>
    
<!-- 슬라이드 시작 -->
    <div class="slide slide_wrap">
        <div class="slide_item">1</div>
        <div class="slide_item">2</div>
        <div class="slide_item">3</div>
        <div class="slide_item">4</div>
        <div class="slide_item">5</div>
        <div class="slide_prev_button slide_button">◀</div>
        <div class="slide_next_button slide_button">▶</div>
        <ul class="slide_pagination"></ul>
    </div>
<!-- 슬라이드 종료 / 도선 Moment 시작 -->
    <div class="d_moment_wrap">
        <h1 class="d_moment"><span class="doseon">도선</span> <span class="moment">MOMENT</span></h1>
        <h2 class="d_moment_subtitle">- 도선사의 소식이 궁금하다면? -</h2>
    </div>
    <div class="d_date_wrap">
        <h1 class="d_date"><span class="doseon">도선</span> <span class="date">DATE</span></h1>
        <h2 class="d_date_subtitle">- 도선사 식구들의 이야기장 -</h2>
    </div>
    <!-- footer 시작 -->
    <div class="footer">

    </div>
</body>
</html>
<script>
    // 슬라이크 전체 크기(width 구하기)
const slide = document.querySelector(".slide");
let slideWidth = slide.clientWidth;

// 버튼 엘리먼트 선택하기
const prevBtn = document.querySelector(".slide_prev_button");
const nextBtn = document.querySelector(".slide_next_button");

// 슬라이드 전체를 선택해 값을 변경해주기 위해 슬라이드 전체 선택하기
const slideItems = document.querySelectorAll(".slide_item");
// 현재 슬라이드 위치가 슬라이드 개수를 넘기지 않게 하기 위한 변수
const maxSlide = slideItems.length;

// 버튼 클릭할 때 마다 현재 슬라이드가 어디인지 알려주기 위한 변수
let currSlide = 1;

// 페이지네이션 생성
const pagination = document.querySelector(".slide_pagination");

for (let i = 0; i < maxSlide; i++) {
if (i === 0) pagination.innerHTML += `<li class="active">•</li>`;
else pagination.innerHTML += `<li>•</li>`;
}

const paginationItems = document.querySelectorAll(".slide_pagination > li");
console.log(paginationItems);

// 버튼 엘리먼트에 클릭 이벤트 추가하기
nextBtn.addEventListener("click", () => {
// 이후 버튼 누를 경우 현재 슬라이드를 변경

currSlide++;

// 마지막 슬라이드 이상으로 넘어가지 않게 하기 위해서
if (currSlide <= maxSlide) {
// 슬라이드를 이동시키기 위한 offset 계산
const offset = slideWidth * (currSlide - 1);
// 각 슬라이드 아이템의 left에 offset 적용
slideItems.forEach((i) => {
    i.setAttribute("style", `left: ${-offset}px`);
});
// 슬라이드 이동 시 현재 활성화된 pagination 변경
paginationItems.forEach((i) => i.classList.remove("active"));
paginationItems[currSlide - 1].classList.add("active");
} else {
currSlide--;
}
});
// 버튼 엘리먼트에 클릭 이벤트 추가하기
prevBtn.addEventListener("click", () => {
// 이전 버튼 누를 경우 현재 슬라이드를 변경
currSlide--;
// 1번째 슬라이드 이하로 넘어가지 않게 하기 위해서
if (currSlide > 0) {
// 슬라이드를 이동시키기 위한 offset 계산
const offset = slideWidth * (currSlide - 1);
// 각 슬라이드 아이템의 left에 offset 적용
slideItems.forEach((i) => {
    i.setAttribute("style", `left: ${-offset}px`);
});
// 슬라이드 이동 시 현재 활성화된 pagination 변경
paginationItems.forEach((i) => i.classList.remove("active"));
paginationItems[currSlide - 1].classList.add("active");
} else {
currSlide++;
}
});

// 브라우저 화면이 조정될 때 마다 slideWidth를 변경하기 위해
window.addEventListener("resize", () => {
slideWidth = slide.clientWidth;
});

// 각 페이지네이션 클릭 시 해당 슬라이드로 이동하기
for (let i = 0; i < maxSlide; i++) {
// 각 페이지네이션마다 클릭 이벤트 추가하기
paginationItems[i].addEventListener("click", () => {
// 클릭한 페이지네이션에 따라 현재 슬라이드 변경해주기(currSlide는 시작 위치가 1이기 때문에 + 1)
currSlide = i + 1;
// 슬라이드를 이동시키기 위한 offset 계산
const offset = slideWidth * (currSlide - 1);
// 각 슬라이드 아이템의 left에 offset 적용
slideItems.forEach((i) => {
    i.setAttribute("style", `left: ${-offset}px`);
});
// 슬라이드 이동 시 현재 활성화된 pagination 변경
paginationItems.forEach((i) => i.classList.remove("active"));
paginationItems[currSlide - 1].classList.add("active");
});
}
</script>

doseonsaSupporters/templates/shared/_navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
</head>
</html>

<ul class="nav">
    <li>
        <a class="q_list" href="{% url 'webzine:webzine' %}">질문목록으로 가기</a>
    </li>
    <li>
        <a class="not" tabindex="-1" aria-disabled="true" href="#">Link</a>
    </li>
    <li>
        <a class="webzine_move" href="{% url 'webzine:question_list'%}">리스트로 이동해요!(과월호 보기)</a>
    </li>
    <li>
        <a class="not" href="#" tabindex="-1" aria-disabled="true">웹진 신청</a>
    </li>
</ul>
<a href="{% url 'main'%}">
    <img src="{% static 'images/도선사 로고.png' %}" alt="안보이지만 사자야">
</a>
{% if user.is_authenticated %} 
    <a href="{% url 'users:logout' %}"> {{user.username }}로그아웃</a>
    <span>||</span>
{% else %}
    <a href="{% url 'users:login' %}">로그인</a>
    <span>||</span>
    <a href="{% url 'users:signup' %}">회원가입</a>
{% endif %}

users/templates/users/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<h1>로그인</h1>
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    {% include 'users/form_errors.html' %}
    <div>
        <label>사용자 ID</label>
        <input type="text" name="username" id="username">
    </div>
    <div>
        <label>비밀번호</label>
        <input type="text" name="password" id="password">
    </div>
    <button type="submit">로그인</button>
</form>
{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <form action="{% url 'users:signup' %}" method="post">
        {% csrf_token %}
        {% include 'users/form_errors.html' %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" name="username" id="username" class="form-control" value="{{form.username.value|default_if_none:''}}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

webzine/templates/webzine/question_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h1 class="border-bottom py-2">{{ a_question.subject }}</h1>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line">
                {{ a_question.content}}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badbe-light py-2">
                    {{ a_question.create_date}}
                </div>
            </div>
        </div>
    </div>
    <div class="border-bottom my-3 py-2">
        {{a_question.answer_set.count}}개의 답변이 있습니다.
        {% for answer in a_question.answer_set.all %}
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">
                    {{ answer.content }}
                </div>
                <div class="d-flex justify-content-end">
                    {{answer.create_date}}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'webzine:answer_create' a_question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{field.label}}</strong>
            {{field.errors}}
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
    </form>
</div>
{% endblock %}

webzine/templates/webzine/question_form.html
{% extends 'base.html' %}
{% block content %}

<div>
    <h5>질문 등록</h5>
    <form method="POST">
        {% csrf_token %}

        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        {{ form.as_p }}
        <button>저장하기</button>
    </form>
</div>

{% endblock %}

webzine/templates/webzine/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h1 class="border-bottom py-2">질문 리스트 보기</h1>
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
            <a href="{% url 'webzine:question_detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <ul>
        {% if question_list.has_previous %}
        <a href="?page={{ question_list.previous_page_number}}">이전</a>
        {% endif %}

        {% for page_number in question_list.paginator.page_range %}
        {% if question_list.number|add:5 >= page_number and page_number >= question_list.number|add:-5 %}
        
        <!-- 현재 페이지 번호랑 같다면 스타일을 다르게 줄 수 있다. -->
        {% if page_number == question_list.number %}
        <li>
            <a href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li>
            <a href="?page={{page_number}}">{{page_number}}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% if question_list.has_next %}
        <a href="?page={{ question_list.next_page_number }}">다음</a>
        {% endif %}
        
    </ul>
    <a href="{% url 'webzine:question_create' %}">질문 등록하기</a>
</div>
{% endblock %}

webzine/templates/webzine/webzine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>웹진이 나올 거야.</h1>
    <a href="/">홈으로 이동해요!</a>
</body>
</html>

webzine/templates/webzine/webzine_upload.html
<form action="{% url 'upload_create' %" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    제목 <br>
    <input type="text" name="title">
    내용 <br>
    <input type="text" name="content"><br>
    사진첨부 <br>
    <input type="file" name="image"><br>
    <input type="submit" value="Submit">
</form>